### ISSUE TITLE
Get-Calendar doesn't show all days of month

### ISSUE THREAD

**Issue by atkinsroy** [jdhitsolutions/PSCalendar#21]
You're only displaying 5 rows of days. Some months require six to show all days. Example August 2021 shows up to the 29th only.

**Comment by jdhitsolutions** [comment]
Hmmm.  I'm not seeing that. What version of the module are you using? What version of PowerShell? What is `$PSCulture`?

![image](https://user-images.githubusercontent.com/12089920/124358344-d445ac00-dbed-11eb-8600-76f36853da45.png)

**Comment by atkinsroy** [comment]
Hi Jeff,
Apologies for the delay:
![image](https://user-images.githubusercontent.com/6621844/124854364-9203dc80-dfea-11eb-951e-2ccbad1a3ddd.png)

**Comment by atkinsroy** [comment]
Works in USA:
![image](https://user-images.githubusercontent.com/6621844/124854649-fb83eb00-dfea-11eb-8541-69e2da8fccfd.png)

**Comment by jdhitsolutions** [comment]
Do you get the same result when running in Windows PowerShell?

**Comment by jdhitsolutions** [comment]
What `Use-Culture` command are you testing with? My testing command doesn't show any differences. And I'm assuming `$PSUICulture` is also `en-AU`.

**Comment by jdhitsolutions** [comment]
Run `Show-Calendar -month August -verbose -highlight 1/8/2021` and post the results

**Comment by jdhitsolutions** [comment]
Ok. In Windows PowerShell testing with culture I get your result.

![image](https://user-images.githubusercontent.com/12089920/124976175-e912ad00-dffc-11eb-8225-2bca33c214e1.png)

**Comment by jdhitsolutions** [comment]
I think there's odd in how .NET returns culture. I seem to be getting different results for en-AU between Windows PowerShell and PowerShell 7. What do you get with this commend? `[system.globalization.cultureinfo]::CurrentCulture.datetimeformat`

**Comment by atkinsroy** [comment]
Same results in Windows PowerShell. Highlight doesn't work. Highlight does work with US formatted date - 8/1/2021 
![image](https://user-images.githubusercontent.com/6621844/125020861-ee373100-e0bc-11eb-8b9a-30657fc3becf.png)

![image](https://user-images.githubusercontent.com/6621844/125021091-5423b880-e0bd-11eb-9126-1098f7316119.png)

![image](https://user-images.githubusercontent.com/6621844/125021140-6a317900-e0bd-11eb-89b3-d4f4ac7ec1ff.png)

$PSUICulture is actually 'au-US' on my system, both in Windows PowerShell and PS7.  This appears to be correct for my locale, checked a couple of systems. I did try changing this to 'en-AU' using the following, but it doesn't change the result.

`[System.Threading.thread]::CurrentThread.CurrentUICulture = "en-AU"`

**Comment by jdhitsolutions** [comment]
Ok. I think I've narrowed down what to look at. I made a few changes in how I'm parsing dates so highlighting is working better now. 

![image](https://user-images.githubusercontent.com/12089920/125080303-aac7cd00-e092-11eb-8c8a-ceedf7de71aa.png)

Obviously, I need to add a week to the calendar if the last day shown is not the last day of the month.

**Comment by atkinsroy** [comment]
Looks good Jeff.

**Comment by jdhitsolutions** [comment]
I am going to leave the issue open because this is a problem on PowerShell 7 because of the .NET problem. I think I will have to come up with a workaround myself instead of waiting on a change to .NET Core.

**Comment by jdhitsolutions** [comment]
This should be better addressed with version 2.2.0 (5f1a7cb). Update the module and try everything out in both versions of Windows.

**Comment by atkinsroy** [comment]
Works with both versions PS. Thanks Jeff.
