### ISSUE TITLE
Ncal doesn't align

### ISSUE THREAD

**Issue by jdhitsolutions** [jdhitsolutions/PSCalendar#25]
If first day in a row is hightlighted it doesn't seem to align property with the ncal command.

**Comment by jdhitsolutions** [comment]
![image](https://user-images.githubusercontent.com/12089920/132350251-65c7f74e-12ee-4443-be73-d8d24e126bba.png)

**Comment by jdhitsolutions** [comment]
This was partially fixed in v.2.3.`. But this still looks like an issue.
![image](https://user-images.githubusercontent.com/12089920/139723867-4c6fb9dc-f848-4225-8c5b-9512234c2e7a.png)

**Comment by atkinsroy** [comment]
FYI, I also get an error with ncal:
![image](https://user-images.githubusercontent.com/6621844/141919585-d5522077-829d-4f43-9c7c-2966a5f8ec42.png)

**Comment by jdhitsolutions** [comment]
I get the same error in Windows PowerShell. I am at a conference this week so I won't be able to get to this until later next week.

**Comment by jdhitsolutions** [comment]
I've made some updates and published a new version to the PowerShell Gallery. Update to v2.6.0 and see if this command works better. It may never be as exact as the native Linux command. But I think it is close.

**Comment by atkinsroy** [comment]
I still see issues with ncal formatting:
![image](https://user-images.githubusercontent.com/6621844/144167117-89359f71-5057-4c4f-b971-cff687eb697c.png)



I had a crack at creating a version that more closely covers the ncal functionality:
![image](https://user-images.githubusercontent.com/6621844/144167247-1f34e790-6443-4da8-a352-c4079c2a77cf.png)

I can share the code with you if you want it.

**Comment by jdhitsolutions** [comment]
This is why I avoid trying to parse strings.

![image](https://user-images.githubusercontent.com/12089920/144248538-c5efa9e0-b936-422c-ae26-1d9913ad7c47.png)

But sure, I'd love to see what you came up with.

**Comment by atkinsroy** [comment]
Here's the link to my attempt.
https://github.com/atkinsroy/ncal

**Comment by jdhitsolutions** [comment]
That was very helpful. The key was your suggestion to pad and then add the formatting.
![image](https://user-images.githubusercontent.com/12089920/144473036-6367ea63-b5f3-4739-b13c-e4c573c9e150.png)

I'll be rolling this out in v2.7.0

**Comment by atkinsroy** [comment]
Check out my latest commit. This was an interesting exercise. Islamic locales are a bit tricky to deal with - did you know Get-Date -Format 'yyyy' is not the same thing as (Get-Date).Year with some locales? 

![image](https://user-images.githubusercontent.com/6621844/145293324-6806538a-db85-4ee4-bc70-f70c6d05e4bc.png)
![image](https://user-images.githubusercontent.com/6621844/145293413-1b383288-c467-4e00-9488-f234c73880ef.png)

**Comment by jdhitsolutions** [comment]
That's interesting. I don't know if I have the time to get this module to work with every possible culture.

**Comment by jdhitsolutions** [comment]
Closing this as  I think the original `ncal` problem has been resolved. I'm open to pull requests to address culture-specific problems.
