### ISSUE TITLE
Issue on comparing start date and end date

### ISSUE THREAD

**Issue by zhijieshi** [jdhitsolutions/PSCalendar#26]
# Problem Report

## What is the syntax or expression you are using?
```
Get-Calendar -start $(get-date) -end $((get-date).addmonths(4))
```

## What Happens?
```
Get-Calendar: Cannot validate argument on parameter 'End'. The end date (03/01/2022 08:44:48) must be later than the start date (11/01/2021 08:44:48)
```
The start date is when the command was run.

## What do you think should happen?
The end date is later than the start date, but the script does not think so.

## Environment Information

```
Name                           Value
----                           -----
PSVersion                      7.1.4
PSEdition                      Core
GitCommitId                    7.1.4
OS                             Microsoft Windows 10.0.19043
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

en-US

2.3.0                PSCalendar                          PSGallery            A PowerShell module to display a calendar in the console.

**Comment by jdhitsolutions** [comment]
I see the problem. I'm trying to validate the parameter with`[ValidateScript()]`. The problem is that the Start parameter value isn't defined until after the command starts running. I could make `-End` a dynamic parameter, but that introduces other challenges.  Adding some validation logic in the Process scriptblock.

**Comment by jdhitsolutions** [comment]
I've pushed v2.3.1 to the PowerShell Gallery. Update the module and try again.

**Comment by zhijieshi** [comment]
Thanks. I checked out the new version. A minor issue. Can you allow end == start?

**Comment by jdhitsolutions** [comment]
If the end date is equal to the start date, that would be the same as simply selecting the month. If I made the change then a command like this:

```powershell
Get-Calendar -Start 10/1/2021 -end 10/1/2021
```

Gives the same result as:

```powershell
Get-Calendar October 2021
```

The module already has this functionality. Or is there a usage pattern I'm not considering?

**Comment by zhijieshi** [comment]
A script I use takes n, a number of months, from the user and displays n months, starting from the current month (starting from the idea of supporting -3 like option to cal.exe on Linux). The code looks like (currently):

```
	elseif ($nmonths -gt 0) {
		Get-Calendar -start $d -end $d.AddMonths($nmonths - 1).AddSeconds(1)    
                # $d is adjusted earlier, so adding 1 second won't get into next day.
	}
```

I guess I could check if `$nmonths` is greater than 1. On the other hand, it seems more intuitive to me if the program can print calendar from month x to month x. 

Thanks for your help and prompt responses.

**Comment by jdhitsolutions** [comment]
So if n = 1 the start and end date are the same??

**Comment by jdhitsolutions** [comment]
I pushed v2.3.2 of the module to the PowerShell Gallery which will allow you to use the same start and end date.

![image](https://user-images.githubusercontent.com/12089920/139925813-a460488d-1de3-482e-a7c7-b6fb9a26eacb.png)

**Comment by zhijieshi** [comment]
Thank you. That's great. 

I also played `show-calendar` a little bit, and put three months next to each other.

```
function show-3months([Datetime]$d)
{
	$winsize = (Get-Host).UI.RawUI.WindowSize

	if ($winsize.width -lt 130 -or $winsize.height -lt 15) {
		Get-Calendar -start $d -end $d.AddMonths(2)
		return
	} 

	$MonthName = (Get-Culture).DateTimeFormat.GetMonthName($d.Month)
	show-calendar -Month $MonthName -Year $d.Year 

	$pos = $host.ui.RawUI.CursorPosition
	$pos.y = $pos.y - 11 

	foreach ($i in 1..2) {
		$pos.x = $pos.x + 44 
		$d = $d.AddMonths(1)
		$MonthName = (Get-Culture).DateTimeFormat.GetMonthName($d.Month)
		show-calendar -Month $MonthName -Year $d.Year -Position $pos 
	}
}
```

![image](https://user-images.githubusercontent.com/45037924/139956888-97511790-f880-4bb4-a8bf-b4da53484ebe.png)

**Comment by jdhitsolutions** [comment]
Nice.
