### ISSUE TITLE
[Feature Request] Display Year in Columns + Command Update - Show Months for Year

### ISSUE THREAD

**Issue by Gana-Dube** [jdhitsolutions/PSCalendar#31]
# Enhancement Request

## Show Months for Year suggestion
Can there be an incorporation of something similar to cal <insert_year>, example cal 2018, and this will give you a view of all the months for that year as opposed to the start and end parameters. Similar to how it's done on Linux.
![image](https://user-images.githubusercontent.com/70259209/156347426-91c46de2-c429-4e1c-96cf-594f77958bd6.png)

## Display Year in Columns
Currently when you view the years months, the view is vertical per row. Can we change that to a horizontal/column monthly view with resizing capabilities.
![image](https://user-images.githubusercontent.com/70259209/156347683-18c09ad1-e59b-4868-a47e-d6b53a18674d.png)

**Comment by jdhitsolutions** [comment]
I may have to completely revise how I display calendars. This is a reasonable request. But not one with an easy fix that comes to mind.

**Comment by jdhitsolutions** [comment]
Adding a parameter to display a year shouldn't be that hard. Formatting to 2 columns, which I think is the best I can fit in a typical console will be tricky.  I don't think I have any control from a PowerShell script on what happens when the window is resized.

**Comment by G-DUBZ** [comment]
Hi Jeff,
The current resize creates an issue of drawing a horizontal line, unless it's only happening on my end, I can't test with another device.
![image](https://user-images.githubusercontent.com/70259209/156587296-362eccc3-594a-4a9b-9d59-1da59d278abc.png)

**Comment by jdhitsolutions** [comment]
I get that too. That is a Windows Terminal artifact.

**Comment by jdhitsolutions** [comment]
Added to v2.9.0
