### ISSUE TITLE
Bug: Empty day trailing day with a different first weekday

### ISSUE THREAD

**Issue by scriptingstudio** [jdhitsolutions/PSCalendar#32]
If the first weekday is Monday the Sunday of the next month will by empty.

### February
![image](https://user-images.githubusercontent.com/17237559/156351380-d3c335d2-6c27-436e-bbd0-91d1c11c2b05.png)

Yellow square is the day of the next month. Why is it highlighted? It is a different month.

### March
![image](https://user-images.githubusercontent.com/17237559/156351397-4b31f041-9d56-4c06-a350-2db923cc9260.png)

![image](https://user-images.githubusercontent.com/17237559/156354253-2e19737f-3408-459b-93d0-afb465fd6406.png)

### April
![image](https://user-images.githubusercontent.com/17237559/156351426-8bb570c3-1306-4f93-b292-362c7e27adea.png)

**Comment by jdhitsolutions** [comment]
I can duplicate this when setting the first day of the week to Monday.

![image](https://user-images.githubusercontent.com/12089920/156381592-d69fb431-eb52-48dc-8ddd-0c9bc75896ce.png)

This appears to be the case with any month where the first day is Monday.

**Comment by scriptingstudio** [comment]
`_getCalendar` function: insert the snippet after line 82 and check it out
```powershell
if ($fd) {
    $day0 += [datetime]$currentDay
}
```

**Comment by scriptingstudio** [comment]
Also, small optimization for block of 118-148 lines
```powerShell
$underline = 4 #$abbreviated[0].Length + 1 (3 or 4)
$days = [System.Collections.Generic.List[object]]::new()
$addday = {
    $d = $abbreviated[$args[0]].padleft($underline, " ")
    if ($NoANSI) {
        $days.add($d)
    } else {
        $days.add(("{0}{1}{2}" -f $PScalendarConfiguration.DayofWeek, $d, "$esc[0m"))
    }
}
$n = if ($fd -eq 0) {0} else {1}
for ($n; $n -lt $abbreviated.count; $n++) {. $addday $n}
if ($fd) {. $addday 0}
```

`$underline` usage:
line 176: `$value = $d.tostring().padleft($underline, ' ')`
line 197: `[int]$pad = (10*$underline - $plainhead.Length) / 2 + 1`

**Comment by jdhitsolutions** [comment]
Thanks for the suggestions.  Fixed the missing day problem. Working on other issues for the next release.

**Comment by jdhitsolutions** [comment]
Added in v2.9.0
