### ISSUE TITLE
[Bug]: Alignment fails with some Asian cultures

### ISSUE THREAD

**Issue by jdhitsolutions** [jdhitsolutions/PSCalendar#33]
### Describe the problem

When running under some Asian cultures the display does not align.

![image](https://user-images.githubusercontent.com/12089920/156584367-fed9c197-aab0-455f-a58f-4454c7fa42a9.png)

### Expectation

Calendar days should align.

### PowerShell version

7.2

### Platform

Windows 11 Pro or Enterprise

### Additional Checks

- [X] You are using the latest version of this module.
- [X] You have read this repository's README file.
- [X] You have read full help and examples for the command you are having problems with.
- [X] You are running PowerShell in an elevated session.
- [X] You are running in a traditional PowerShell console or Windows Terminal

**Comment by scriptingstudio** [comment]
I will allow myself to comment on this issue.
I am afraid it is impossible or will take disparate efforts. Short day name length can vary across week. True day name length does not correspond to visual length. 
It is so complicated that I dont see the way to solve the task. I spent so much time to struggle with asian cultures that I dont see the light on this question.

**Comment by jdhitsolutions** [comment]
I would agree with that assessment. I haven't had anyone report this as a problem so I'm probably worrying over nothing.

**Comment by scriptingstudio** [comment]
Don't think me a bore but one more thing.
We proceed from the assumption that only Sunday or Monday can be the first day of week but the world is a bit more diverse. And any other `FirstDay` produces amess in output.

Statistics on cultures:
```powershell
[system.globalization.cultureinfo]::GetCultures('allCultures') | . { process {
    [pscustomobject]@{
        Culture = $_.DisplayName
        Id      = $_.name
        FDW     = [system.globalization.cultureinfo]::new($_.name).DateTimeFormat.FirstDayOfWeek
    }
}} | Group-Object fdw -NoElement

Count Name
----- ----
  250 Sunday
   41 Saturday
  598 Monday
```

**Comment by scriptingstudio** [comment]
I solved the problem for invariant first day of week
```powershell
# add enough days to finish the week
$weekindex = (0..6+0..6)[$fd..($fd + 6)]
$lastday = $weekindex[-1]
While ($currentDay.DayOfWeek.value__ -ne $lastday) {
    [datetime]$aDay = $currentDay
    Switch ($aDay.DayOfWeek.value__) {
        0 { $day0.add($aday) }
        1 { $day1.add($aday) }
        2 { $day2.add($aday) }
        3 { $day3.add($aday) }
        4 { $day4.add($aday) }
        5 { $day5.add($aday) }
        6 { $day6.add($aday) }
    }
    $Currentday = $currentDay.AddDays(1)
}
switch ($fd) {
    1 {$day0.add([datetime]$currentDay)}
    2 {$day1.add([datetime]$currentDay)}
    3 {$day2.add([datetime]$currentDay)}
    4 {$day3.add([datetime]$currentDay)}
    5 {$day4.add([datetime]$currentDay)}
    6 {$day5.add([datetime]$currentDay)}
    0 {$day6.add([datetime]$currentDay)}
}
# remove orphan week
$fdw = (Get-Variable "day$fd").Value
if ($fdw[-1].month -ne $start.month) {
    $i = $fdw.count - 1
    switch (0..6) {
        1 {$day0.RemoveAt($i)}
        2 {$day1.RemoveAt($i)}
        3 {$day2.RemoveAt($i)}
        4 {$day3.RemoveAt($i)}
        5 {$day4.RemoveAt($i)}
        6 {$day5.RemoveAt($i)}
        0 {$day6.RemoveAt($i)}
    }
}
```

**Comment by jdhitsolutions** [comment]
Closing and tagging as `Won't fix`. I have no way of truly testing this, and I each Asian culture will require a different setting. If this is an issue for a user running under an Asian culture, my recommendation is that they fork this project and modify the code to meet their cultural settings.
