### ISSUE TITLE
RuntimeException with version 5.1 windows powershell

### ISSUE THREAD

**Issue by Tr4pSec** [jdhitsolutions/PSCalendar#9]
Running Show-Calendar gives:

> Cannot convert value "31.01.2019 00:00:00" to type "System.DateTime". Error: "String was not recognized as a valid DateTime."
> At C:\Program Files\WindowsPowerShell\Modules\PSCalendar\1.5.1\calendar-functions.ps1:111char:21
>                      $highlightDates += (Get-Date).date.toString()
>                      ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
>      CategoryInfo          : InvalidArgument: (:) [], RuntimeException
>      FullyQualifiedErrorId : InvalidCastParseTargetInvocationWithFormatProvider
> 
> 

Before showing the calendar as intended. 

![image](https://user-images.githubusercontent.com/27040764/52058547-f7c12400-2567-11e9-9c54-c7075bed276d.png)

The error occurs about 30+ times before calendar is shown. 

![image](https://user-images.githubusercontent.com/27040764/52058624-23dca500-2568-11e9-9155-591f1784a47f.png)

**Comment by Tr4pSec** [comment]
Could it be something with me living in europe, and using Day,Month,Year instead of Month,Day,Year?

**Comment by jdhitsolutions** [comment]
It very well could be.  If you run Get-Culture what are you using? And show me the command you were using.

**Comment by jdhitsolutions** [comment]
But you should also be able to run the command specifying the month and year. You should get autocompletion for the month.

**Comment by jdhitsolutions** [comment]
That is helpful. Thanks. I will have to find a way to better accommodate different cultures.

**Comment by Tr4pSec** [comment]
I tried recreating the error:

![image](https://user-images.githubusercontent.com/27040764/52065982-ef70e500-2577-11e9-8550-e8dd7ccced93.png)

**Comment by jdhitsolutions** [comment]
Sorry this slipped off my plate. See if the changes I made in v1.6 make a difference.

**Comment by ormoru** [comment]
Version 1.6 still show me an error.
I try remove '.toString()' at line 112 and 113 and function is ok.

From this:
```
if ($highlightDates -ne (Get-Date).date.toString() ) {
  $highlightDates += (Get-Date).date.toString()
}

```
To:

```
if ($highlightDates -ne (Get-Date).date ) {
  $highlightDates += (Get-Date).date
}

```

**Comment by jdhitsolutions** [comment]
Install v1.7.0 from the PowerShell Gallery and see if it works better for you. If not, run your command -Verbose and show me the output.

**Comment by JaekelEDV** [comment]
This did it for me. 1.7 from PSGallery runs without errors in de-DE.

**Comment by Tr4pSec** [comment]
Also works for me now. Closing
